# Generated by Django 3.2 on 2022-11-20 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('desc', models.TextField(max_length=10000, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Of Publish')),
            ],
        ),
    ]
