# Generated by Django 3.2 on 2022-11-28 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221121_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Hot Tea', 'Hot Tea'), ('Hot Drink', 'Hot Drink'), ('Cold Coffee', 'Cold Coffee'), ('Iced Tea', 'Iced Tea'), ('Cold Drink', 'Cold Drink'), ('Hot Breakfast', 'Hot Breakfast'), ('Bakery', 'Bakery'), ('Lunch', 'Lunch'), ('Snacks&Sweets', 'Snacks&Sweets')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
